# Generated by Django 3.0.4 on 2020-03-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='choice_A',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='choice_B',
            new_name='choice1',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='choice_C',
            new_name='choice2',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='correct',
            new_name='choice3',
        ),
        migrations.AddField(
            model_name='questions',
            name='choice4',
            field=models.CharField(default='', max_length=50),
        ),
    ]
